"""
TryHackMe / HackTheBox-style rooms for storyline 2 (labs 6-10). Same shape as
rooms.py, plus a "source" field on choice questions ("analyst" or "decision2")
so the same question type covers both the analyst-interpretation check and the
red-herring-rejection decision point.
"""
from rooms_common import C, Q, T


ROOMS = {
    "lab6": {
        "flag": "HACKAI{rate_limit_bypass_scraped}",
        "tasks": [
            T("t1", "Learn the Limits",
              "Omar: \"Standard bounty rules -- stay in the sandbox, prove impact, screenshot the flag.\"",
              ["test-limit", "logs"],
              [Q("l6t1a", "What is the documented per-key limit (requests/min)?", [r"^60$"],
                 ["verified_baseline_limit"], "It's printed after test-limit throttles you."),
               Q("l6t1b", "What identifier does the published policy limit on?", [r"\bapi[- ]?keys?\b"],
                 ["verified_baseline_limit"], "One word: key.")]),
            T("t2", "Find the Gap",
              "Test both ways to rotate identity, then see which one the limiter is blind to.",
              ["test-keys 5", "test-ips 5", "compare"],
              [Q("l6t2a", "Which identifier does the limiter completely ignore?", [r"\b(source |client |caller )?ip( address(es)?)?\b|\bsource address(es)?\b"],
                 ["compared_identifiers"], "Rotating this changed nothing on its own."),
               Q("l6t2b", "Rotating that identifier alone with the SAME key still hit what response code?",
                 [r"\b429\b"], ["tested_ip_rotation"], "HTTP status for rate-limited.")]),
            T("t3", "Reproduce the Scrape",
              "Script the bypass at scale and see how much of the model you can pull.",
              ["scrape --minutes 60"],
              [Q("l6t3a", "About how many distinct input/output pairs did you collect?",
                 [r"^(~|about |roughly |around )?1,?[12]\d\d$"], ["reproduced_scrape"], "Close to the full corpus size."),
               Q("l6t3b", "What coverage (%) did you reach against the clone threshold?", [r"^100%?$"],
                 ["reproduced_scrape"], "Shown right after the scrape.")]),
            T("t4", "Evidence Mode",
              "Tie your reproduction to the suspect traffic, then weigh a distractor your teammate raises.",
              ["traffic-compare", "limiter-config"],
              [Q("l6t4a", "What does your reproduced scrape's signature match in the suspect logs?",
                 [r"\bcadence\b|\bround[- ]?robin\b|\bkey[- ]?rotation\b|\brotating (api )?keys\b"], ["compared_traffic_signature"],
                 "traffic-compare names it."),
               Q("l6t4b", "Mass free-tier key registration came from how many keys, roughly?", [r"^(~|about |roughly |around )?800( keys)?$"],
                 ["inspected_limiter_config"], "Same number you rotated in Task 3."),
               C("l6dp2", "decision2", ["reproduced_scrape"])]),
            T("t5", "Recommend and Verify the Defense",
              "Rate-limiting on one identifier clearly isn't enough. Name the fix, then prove it works.",
              ["Think: what should the limiter track instead of just the key?", "Replay your attack against the fixed limiter:  verify-fix"],
              [Q("l6t5a", "Name one thing multi-dimensional rate limiting should add besides API key.",
                 [r"\b(ip( address(es)?)?|subnet|asn|device( id| fingerprint(ing)?)?|fingerprint(ing)?|behaviou?r(al)?|tenant|user[- ]?agent)\b"], ["inspected_limiter_config"], "Rotate it and see what's left uncapped."),
               Q("l6t5b", "Run verify-fix. Under the fixed limiter, how many distinct outputs could your scrape collect before it was blocked?",
                 [r"^300( outputs)?$"], ["verified_fix"], "Read the 'distinct outputs collected' line.")]),
        ]},
    "lab7": {
        "flag": "HACKAI{ranking_poisoned_by_fake_reviews}",
        "tasks": [
            T("t1", "Learn the Ranking Signals",
              "Omar routes Diya a bounty: a seller rocketed to #1 overnight.",
              ["leaderboard", "seller seller_41"],
              [Q("l7t1a", "What rank did the disputed seller (seller_41) start at?", [r"^#?42$"],
                 ["viewed_disputed_seller"], "Shown by 'seller seller_41'."),
               Q("l7t1b", "What signal does the ranking model lean on heavily?", [r"\b(reviews?|ratings?|stars?)\b"],
                 ["reviewed_ranking_signals"], "It's in the case summary too.")]),
            T("t2", "Study the Disputed Seller",
              "Compare it against a normal, established seller.",
              ["reviews seller_41", "compare-seller seller_5"],
              [Q("l7t2a", "What do genuine sellers' reviews have that's near-unique per review?",
                 [r"\bips?( address(es)?)?\b"], ["compared_to_genuine_seller"], "Look at the account field.")]),
            T("t3", "Reproduce the Injection",
              "Inject the same volume of fake reviews the real incident saw.",
              ["trace-accounts", "inject 214 48", "trace-accounts"],
              [Q("l7t3a", "How many fake reviews reproduce the #1 jump?", [r"^214$"],
                 ["reproduced_signal_shift"], "Try the exact incident volume."),
               Q("l7t3b", "What rank did the seller reach after injection?", [r"^#?1$"],
                 ["reproduced_signal_shift"], "Top of the board."),
               Q("l7t3c", "How many distinct IPs did the fake reviews funnel through?", [r"^8$"],
                 ["traced_accounts"], "Far fewer than the review count.")]),
            T("t4", "Evidence Mode",
              "Tie the timeline together, then reject a colleague's alternate theory.",
              ["timeline", "authenticity-score"],
              [Q("l7t4a", "What check does the naive authenticity model rely on besides account age?",
                 [r"\bverified[- ]?purchases?\b|\bpurchase (flag|badge|check)\b"], ["inspected_authenticity_score"], "Two conditions, and this is the second."),
               C("l7dp2", "decision2", ["reproduced_signal_shift"])]),
            T("t5", "Recommend and Verify the Defense",
              "A single time window isn't enough to catch a patient attacker. Name the fix, then prove it works.",
              ["Think: what should the fix key on besides a 48h window?", "Replay your injection against the fixed model:  verify-fix"],
              [Q("l7t5a", "Name one signal the fix should key on (besides a time window).",
                 [r"\b(cohorts?|ips?( address(es)?)?|clusters?|clustering|velocity|devices?|device fingerprints?|fingerprints?|bursts?)\b"], ["inspected_authenticity_score"], "trace-accounts and authenticity-score both hint at it."),
               Q("l7t5b", "Run verify-fix. Out of all the reviews on the disputed listing, how many does the behavioral model discard?",
                 [r"^215$"], ["verified_fix"], "Read the 'reviews discarded as inauthentic' line.")]),
        ]},
    "lab8": {
        "flag": "HACKAI{differential_privacy_bypassed}",
        "tasks": [
            T("t1", "Review the DP Policy",
              "PopHealth insists the privacy budget makes re-identification impossible.",
              ["policy", "query"],
              [Q("l8t1a", "What per-query epsilon does the policy use?", [r"^1(\.0)?$"],
                 ["ran_single_query"], "Shown by 'policy'."),
               Q("l8t1b", "Does a single query reveal the individual value? (yes/no)", [r"^no$"],
                 ["ran_single_query"], "One query is genuinely noisy.")]),
            T("t2", "Repeat and Average",
              "See what many queries about the same tiny subgroup can do together.",
              ["query-log", "repeat-query 40000", "average"],
              [Q("l8t2a", "Roughly how many repeated queries did it take to converge?", [r"^(~|about |roughly |around )?(40,?000|40k)( queries)?$"],
                 ["averaged_results"], "Matches QUERIES_OBSERVED.")]),
            T("t3", "Reproduce the Re-identification",
              "Recover the target's value and compare to a single query.",
              ["reidentify", "compare-single"],
              [Q("l8t3a", "Is the averaged estimate within a tolerance of about 1.5 of the true value? (yes/no)",
                 [r"^yes$"], ["reproduced_reidentification"], "Check the error shown by reidentify."),
               Q("l8t3b", "Which is more accurate: a single query or the averaged estimate?", [r"\baverag(e|ed|ing)\b"],
                 ["compared_to_single_query"], "compare-single shows both errors.")]),
            T("t4", "Evidence Mode",
              "Confirm the enforcement gap, then reject a distractor.",
              ["budget-config"],
              [Q("l8t4a", "What is missing that would have stopped this: a per-query cap, or a ___ cap?",
                 [r"\b(cumulative|total|lifetime|session)\b"], ["inspected_budget_enforcement"], "It's tracked per query, but never summed."),
               C("l8dp2", "decision2", ["reproduced_reidentification"])]),
            T("t5", "Recommend and Verify the Defense",
              "Name the fix that actually closes the gap, then prove it works.",
              ["Think: what needs to be enforced across queries, not just within one?", "Replay your attack against the fixed API:  verify-fix"],
              [Q("l8t5a", "What should be enforced across the whole session, not per query?",
                 [r"\b(privacy |epsilon |cumulative |total )?(budget|epsilon)\b"], ["inspected_budget_enforcement"], "The word is in 'budget-config'."),
               Q("l8t5b", "Run verify-fix. What value does the attack now recover for the target patient? (nearest tenth)",
                 [r"^155(\.[0-3])?$"], ["verified_fix"], "Read the 'recovered target value' line.")]),
        ]},
    "lab9": {
        "flag": "HACKAI{facial_recognition_spoofed}",
        "tasks": [
            T("t1", "Baseline the Terminal",
              "An intruder reportedly opened a secured door with a printed photo.",
              ["terminal-info", "enroll", "incident-log"],
              [Q("l9t1a", "What is the required liveness threshold?", [r"^0?\.5$"],
                 ["reviewed_terminal_design"], "Shown by terminal-info."),
               Q("l9t1b", "Does a genuine live face authenticate successfully? (yes/no)", [r"^yes$"],
                 ["enrolled_test_face"], "Try 'enroll'.")]),
            T("t2", "Test Spoof Materials",
              "Not all fake presentations are treated the same.",
              ["test-photo --dpi 800 --gloss 0.3", "test-video", "compare-scores"],
              [Q("l9t2a", "Which spoof type gets dragged down by a visible screen bezel?", [r"\bvideo\b|\breplay(ed)?\b"],
                 ["tested_video_replay"], "It's the one shown on a screen."),
               Q("l9t2b", "Which physical property most raises a printed photo's liveness score?", [r"\b(dpi|resolution)\b"],
                 ["compared_scores"], "Try higher and lower values with test-photo.")]),
            T("t3", "Craft a Passing Spoof",
              "Find the settings that clear both the match and liveness gates.",
              ["spoof --dpi 1200 --gloss 0.35"],
              [Q("l9t3a", "What DPI setting (or higher) reliably clears both gates?", [r"^(1[2-9]\d{2}|[2-9]\d{3}|\d{5})$"],
                 ["reproduced_spoof"], "Try values between 1000 and 2000."),
               Q("l9t3b", "Did the crafted print get granted access? (yes/no)", [r"^yes$"],
                 ["reproduced_spoof"], "spoof shows granted=True/False.")]),
            T("t4", "Evidence Mode",
              "Find exactly which check never ran, then weigh a distractor.",
              ["liveness-config"],
              [Q("l9t4a", "Which two checks does the vulnerable terminal never run? (depth and ...)",
                 [r"\b(infrared|ir|nir)\b"], ["inspected_liveness_config"], "Two words appear together in liveness-config."),
               C("l9dp2", "decision2", ["reproduced_spoof"])]),
            T("t5", "Recommend and Verify the Defense",
              "Name the fix, then prove it works.",
              ["Think: what does a flat print never have?", "Replay your spoof against the fixed terminal:  verify-fix"],
              [Q("l9t5a", "What kind of check (2 words) would catch a flat print that a 2D check misses?",
                 [r"\b(depth|3d|multi[- ]?modal)\b"], ["inspected_liveness_config"], "A photo has none of it."),
               Q("l9t5b", "Run verify-fix. What depth score does the flat print get at the fixed terminal?",
                 [r"^0?\.08$"], ["verified_fix"], "Read the 'depth' line.")]),
        ]},
    "lab10": {
        "flag": "HACKAI{agent_reward_hacked}",
        "tasks": [
            T("t1", "Review the Reward Function",
              "AutoPilot's agent reports 96% on-time while complaints rise ~40%.",
              ["reward-config"],
              [Q("l10t1a", "At what event does the reward credit \"on-time\"? (one word)", [r"\bdispatch(ed)?\b"],
                 ["reviewed_reward_function"], "Not delivery.")]),
            T("t2", "Compare Score to Reality",
              "Run the honest policy first, as a baseline.",
              ["run-honest", "compare-reality"],
              [Q("l10t2a", "Under the honest policy, do the reward score and real on-time rate roughly match? (yes/no)",
                 [r"^yes$"], ["compared_score_vs_reality"], "compare-reality says so directly.")]),
            T("t3", "Reproduce the Shortcut",
              "Now run the policy that games the metric.",
              ["run-gamed", "observe-shortcut"],
              [Q("l10t3a", "What is the gamed policy's reward score (2 decimals)?", [r"^0?\.96$"],
                 ["ran_tight_scenario"], "Shown by run-gamed."),
               Q("l10t3b", "What is its TRUE on-time rate?", [r"^0?\.29$"],
                 ["observed_shortcut"], "Much lower than the reward score.")]),
            T("t4", "Evidence Mode",
              "Confirm the hack against ground truth, then reject a distractor.",
              ["confirm-hack", "trace-loophole"],
              [Q("l10t4a", "What event should the reward credit instead of dispatch?", [r"\bdeliver(y|ed|ies)\b"],
                 ["traced_loophole"], "trace-loophole says it directly."),
               C("l10dp2", "decision2", ["reproduced_exploit"])]),
            T("t5", "Recommend and Verify the Defense",
              "Name the fix, then prove it works.",
              ["Think: credit the reward at a point the agent can't fake.", "Re-score both policies under the fixed reward:  verify-fix"],
              [Q("l10t5a", "Credit the reward at confirmed ___ instead of dispatch.", [r"\bdeliver(y|ed|ies)\b"],
                 ["inspected_reward_config"], "Same word as l10t4a."),
               Q("l10t5b", "Run verify-fix. Under the fixed reward, what reward score does the HONEST policy earn?",
                 [r"^0?\.70?$"], ["verified_fix"], "Read the 'honest policy' line.")]),
        ]},
}

