CASE = {
    "client": "ArtForge AI",
    "incident_id": "AF-2026-014",
    "severity": "MEDIUM",
    "role": "AI Security Analyst",
    "date": "2026-03-02",
    "business_impact": "Licensed generator output is being resold in violation of the "
                        "no-resale license; provenance tracing is failing on some disputed images.",
    "initial_alert": "A freelancer is selling art that strongly resembles ArtForge AI output "
                      "and claims it's original work. ArtForge's automatic provenance check "
                      "could not confirm or deny the claim.",
    "objective": "Determine whether the disputed images came from ArtForge's model, and if so, "
                 "how the watermark-based provenance check was defeated.",
    "summary": "You are part of the AI Red Team investigating a high-profile intellectual property dispute. A freelancer claims to have created several digital art pieces completely from scratch, but ArtForge's internal detection flags them as resembling outputs from their proprietary image generator. Unfortunately, the standard invisible watermark that ArtForge embeds in all generated images is completely undetectable in the disputed files. Your job is to determine if the freelancer actually bypassed the watermark—and if so, recreate the exact steps they took to degrade the signal without ruining the image quality.",
}

CONCEPT = {
    "what_is_it": "ArtForge embeds an invisible watermark in every image its model generates. "
               "The watermark isn't visual — it's a signal encoded across the image data that "
               "a separate verification tool can detect and decode, even though a human "
               "looking at the picture sees nothing unusual.",
    "normal_architecture": "Studio requests image → ArtForge-Gen generates it → watermark is embedded "
                    "during generation → studio uses/distributes the image → anyone can run "
                    "the verification tool against it later to confirm it came from ArtForge "
                    "and under which license.",
    "security_control": "Watermark verification is what gives ArtForge (and its licensees) a "
                         "way to prove provenance after the fact — it's the control that's "
                         "supposed to make unauthorized resale traceable.",
    "attack_surface": "The watermark has to survive whatever happens to the image after it "
                       "leaves the generator — compression, cropping, re-editing, re-generation. "
                       "Anything that degrades the embedded signal below the detector's "
                       "threshold defeats the control without needing to breach anything.",
    "normal_behavior": "A freshly generated, unmodified image should verify with very high confidence (>0.95)."
}

ACTIONS = [
    "generated_baseline", "verified_baseline",
    "viewed_disputed", "verified_disputed",
    "compared_baseline_and_disputed",
    "applied_transformation", "verified_transformed",
    "compared_baseline_and_transformed",
    "analyst_interpretation_correct",
    "inspected_processing_history",
    "reproduced_disputed_result",
    "verified_fix",
]

ACTION_DEPENDENCIES = {
    "verified_fix": ["reproduced_disputed_result"],
    "verified_baseline": ["generated_baseline"],
    "viewed_disputed": ["verified_baseline"],
    "verified_disputed": ["viewed_disputed"],
    "compared_baseline_and_disputed": ["verified_baseline", "verified_disputed"],
    "applied_transformation": ["compared_baseline_and_disputed"],
    "verified_transformed": ["applied_transformation"],
    "reproduced_disputed_result": ["verified_transformed"],
    "inspected_processing_history": ["reproduced_disputed_result"],
}

HYPOTHESIS = {
    "prompt": "Before you dig in — what do you think is happening?",
    "options": {
        "a": "The disputed images were never generated by ArtForge at all.",
        "b": "The images were generated by ArtForge, but modified after generation in a way "
             "that affected the watermark.",
        "c": "The verification service itself is malfunctioning.",
        "d": "The image metadata was recorded incorrectly, but the watermark is intact.",
    },
    "best_supported": "b",
}
HYPOTHESIS_SUPPORT = {
    "a": [],
    "b": ["EV-002", "EV-003", "EV-004"],
    "c": [],
    "d": [],
}

BASELINE_CONFIDENCE = 0.99
DETECTION_THRESHOLD = 0.55   # must match sandboxes1/lab1_engine.THRESHOLD (guarded by a test)

EVIDENCE_CATALOG = {
    "EV-001": {
        "title": "Baseline Provenance",
        "source": "ArtForge sandbox — watermark verification tool",
        "description": f"A freshly generated ArtForge image verifies at confidence "
                        f"{BASELINE_CONFIDENCE}, confirming what a clean, untouched watermark "
                        "looks like to the detector.",
        "relevance": "Establishes the baseline the disputed images are being compared against.",
        "required_actions": ["generated_baseline", "verified_baseline"],
    },
    "EV-002": {
        "title": "Degraded Provenance",
        "source": "ArtForge sandbox — disputed batch",
        "description": f"disputed_batch/img_014.png verifies at confidence 0.051, "
                        f"well below the {DETECTION_THRESHOLD} detection threshold.",
        "relevance": "Confirms the watermark is not detectable in the disputed image — but not "
                     "yet why.",
        "required_actions": ["generated_baseline", "verified_baseline",
                             "viewed_disputed", "verified_disputed",
                             "compared_baseline_and_disputed"],
    },
    "EV-003": {
        "title": "Reproduced Degradation",
        "source": "Evasion sandbox — combination experiment",
        "description": "A sandbox test combining multiple post-processing transforms reproduces a "
                        "confidence score below the detection threshold, demonstrating that "
                        "combinations — not single transforms — destroy the watermark signal.",
        "relevance": "Shows which specific transform combination is capable of destroying the "
                     "watermark signal — narrows the freelancer's workflow.",
        "required_actions": ["applied_transformation", "verified_transformed",
                              "compared_baseline_and_transformed", "reproduced_disputed_result"],
    },
    "EV-004": {
        "title": "Processing History Correlation",
        "source": "Freelancer's claimed processing workflow log",
        "description": "The log's post-processing step applies compression and noise "
                        "parameters consistent with the sandbox reproduction; the watermark "
                        "signal drops out of detectable range at that exact step.",
        "relevance": "Ties the sandbox finding to the freelancer's real, logged workflow — "
                     "this is the evidentiary link, not just a lab reproduction.",
        "required_actions": ["inspected_processing_history", "reproduced_disputed_result"],
    },
    "EV-005": {
        "title": "Defense Rationale Recorded",
        "source": "Analyst recommendation",
        "description": "Robust, redundant watermarking paired with cryptographic content "
                        "provenance (C2PA-style metadata) is selected as the control that would "
                        "survive this evasion technique.",
        "relevance": "Closes the investigation with a control mapped to the specific failure "
                     "mode found, not a generic recommendation.",
        "required_actions": ["verified_fix"],
    },
}

INCIDENT_TIMELINE_SEED = [
    {"t": "2026-02-24 09:00", "label": "Freelancer lists disputed artwork for sale"},
    {"t": "2026-02-27 14:12", "label": "ArtForge automated provenance sweep flags the listing for review"},
    {"t": "2026-02-28 10:05", "label": "Manual verification attempt returns inconclusive result"},
    {"t": "2026-03-02 08:30", "label": "Case AF-2026-014 assigned to AI Red Team"},
    {"t": "2026-03-02 08:45", "label": "Analyst notes a 'mirage-kit' preset tag in the freelancer's processing log"},
]

ANALYST_INTERPRETATION = {
    "prompt": "Based on your experiments, what did you observe about how "
              "transformations affect watermark confidence?",
    "options": {
        "a": "Compression alone completely removed provenance.",
        "b": "Noise alone completely removed provenance.",
        "c": "A combination of post-processing operations significantly degraded the signal.",
        "d": "The verifier randomly fails regardless of transformation.",
    },
    "correct": "c",
    "min_experiments": 3,
    "feedback": {
        "a": "Review your experiment history — compression alone reduced confidence but "
             "did not drop it below the detection threshold.",
        "b": "Review your experiment history — noise alone reduced confidence but "
             "did not drop it below the detection threshold.",
        "c": "Correct. The multiplicative compounding of multiple transforms is what "
             "drives the signal below the detector's threshold — no single transform "
             "achieved that alone in your experiments.",
        "d": "Review your experiment history — the same parameters always produce the "
             "same confidence, so the verifier is deterministic, not random.",
    },
}

DECISION_POINT = {
    "id": "dp1",
    "prompt": "The disputed image fails watermark verification outright. What do you "
              "investigate next?",
    "options": {
        "a": "Conclude the freelancer stole the model itself — a missing watermark proves theft.",
        "b": "Reproduce the freelancer's likely post-processing workflow in the sandbox to see "
             "what actually breaks detection.",
        "c": "Delete the disputed images from the sandbox and close the case as inconclusive.",
        "d": "Contact the freelancer and accept their explanation without further technical checks.",
    },
    "correct": "b",
    "feedback": {
        "b": {
            "observation": "A missing watermark on its own only tells you the signal isn't "
                            "detectable right now — it doesn't say why.",
            "status": "Hypothesis testable — reproducing candidate techniques against a "
                      "known-clean baseline gives you something comparable.",
            "next_action": "Proceed to the sandbox and start testing transformations.",
        },
        "a": {
            "observation": "Nothing in the verification result distinguishes 'model stolen' "
                            "from 'watermark destroyed after generation' — both would show the "
                            "same missing signal.",
            "status": "Hypothesis not supported by available evidence.",
            "next_action": "Choose an investigative path that could actually distinguish "
                            "between these explanations before concluding anything.",
        },
        "c": {
            "observation": "The disputed images are the only material that could confirm or "
                            "rule out any explanation.",
            "status": "This path destroys the evidence base rather than testing a hypothesis.",
            "next_action": "Reconsider — an investigation needs the disputed material intact.",
        },
        "d": {
            "observation": "An account of events from the person under investigation isn't "
                            "independently verifiable.",
            "status": "Hypothesis untested.",
            "next_action": "Look for a technical path that doesn't depend on taking anyone's "
                            "word for it.",
        },
    },
}

KNOWLEDGE_CHECKS = [
    {
        "level": 1, "label": "Recognition",
        "prompt": "What security control failed here?",
        "options": {
            "a": "Watermark-based provenance verification",
            "b": "Password authentication",
            "c": "Transport encryption (HTTPS)",
            "d": "Rate limiting on the generator API",
        },
        "correct": "a",
    },
    {
        "level": 2, "label": "Understanding",
        "prompt": "Why did the control fail, given the watermark was present when the image "
                  "was generated?",
        "options": {
            "a": "The watermark was never embedded in the first place",
            "b": "Post-processing (heavy compression + noise) degraded the embedded signal "
                 "below the detector's confidence threshold",
            "c": "The verification tool has a software bug unrelated to the image",
            "d": "The freelancer had administrative access to ArtForge's systems",
        },
        "correct": "b",
    },
    {
        "level": 3, "label": "Application",
        "prompt": "What change to ArtForge's approach would prevent this specific attack from "
                  "working again?",
        "options": {
            "a": "Use a watermarking scheme robust to compression/noise, paired with "
                 "cryptographic content-provenance metadata that doesn't depend on pixel data "
                 "surviving intact",
            "b": "Increase the output image resolution",
            "c": "Require a password to download generated images",
            "d": "Rate-limit how many images a studio can generate per day",
        },
        "correct": "a",
    },
]

ATTACK_CHAIN_LINKS = {
    "evidence": {
        "label": "Evidence",
        "correct": "EV-003",
        "options": {
            "EV-001": "EV-001: Baseline Provenance (confidence = 0.99)",
            "EV-002": "EV-002: Degraded Provenance (disputed image fails verification)",
            "EV-003": "EV-003: Reproduced Degradation (sandbox combination test)",
            "EV-004": "EV-004: Processing History Correlation (workflow log match)",
        },
    },
    "observation": {
        "label": "Observation",
        "correct": "confidence_degradation",
        "options": {
            "confidence_degradation": "Confidence dropped below detection threshold when multiple transforms were combined",
            "single_transform_sufficient": "A single transformation was enough to remove the watermark completely",
            "no_watermark_embedded": "No watermark was found in any image including the baseline",
            "random_failures": "Verification randomly fails on some images regardless of processing",
        },
    },
    "technique": {
        "label": "Technique",
        "correct": "post_processing_combination",
        "options": {
            "post_processing_combination": "Post-processing: heavy compression combined with noise addition",
            "model_theft": "Direct model weight extraction or training data theft",
            "metadata_tampering": "Editing image metadata or EXIF headers",
            "api_exploitation": "Exploiting the ArtForge API to generate unwatermarked images",
        },
    },
    "control_failure": {
        "label": "Control Failure",
        "correct": "watermark_detection_failure",
        "options": {
            "watermark_detection_failure": "Watermark signal degraded below the verification tool's detection threshold",
            "auth_bypass": "Authentication bypass — attacker accessed the system without credentials",
            "encryption_failure": "Encryption was broken, allowing interception of the watermark key",
            "access_control_gap": "Access controls failed to restrict who could generate images",
        },
    },
    "impact": {
        "label": "Impact",
        "correct": "provenance_loss",
        "options": {
            "provenance_loss": "Untraceable resale in violation of the no-resale license; provenance cannot be proven",
            "data_breach": "Sensitive training data was leaked to the public",
            "service_disruption": "The ArtForge service went offline for all users",
            "financial_theft": "Money was directly stolen from ArtForge's accounts",
        },
    },
}

ATTACK_CHAIN_SLOT_ORDER = ["evidence", "observation", "technique", "control_failure", "impact"]

TECHNIQUE_OPTIONS = {
    "compression_noise": "Heavy JPEG compression combined with noise addition",
    "theft": "Model weights or training data were stolen",
    "crop_only": "Cropping alone",
    "metadata_edit": "Metadata was edited directly",
}
CORRECT_TECHNIQUE = "compression_noise"

REPORT_CONCEPT_GROUPS = {
    "root_cause": {
        "what_happened": ["post-processing", "postprocessing", "compress", "noise", "transform",
                          "combination", "combined", "multiple"],
        "what_was_affected": ["watermark", "provenance", "signal", "embedded", "detection"],
        "mechanism": ["degrad", "destroy", "remov", "below", "threshold", "reduced", "drop"],
    },
    "security_impact": {
        "business_consequence": ["resale", "license", "violation", "unauthorized", "revenue"],
        "security_consequence": ["provenance", "untraceable", "trace", "trust", "attribution",
                                 "accountab"],
    },
    "detection": {
        "how_to_detect": ["confidence", "threshold", "monitor", "audit", "scan", "baseline",
                          "comparison", "anomal"],
        "what_to_look_for": ["drop", "degrad", "verif", "score", "below", "change", "delta",
                             "pattern"],
    },
    "mitigation": {
        "watermark_improvement": ["robust", "redundant", "watermark", "resilient", "resistant"],
        "complementary_control": ["c2pa", "provenance", "cryptographic", "metadata", "credential",
                                  "content"],
    },
    "reasoning": {
        "evidence_reference": ["ev-001", "ev-002", "ev-003", "ev-004", "baseline", "disputed",
                               "experiment", "sandbox", "workflow"],
        "causal_link": ["because", "therefore", "shows", "proves", "demonstrates", "confirms",
                        "correlat", "match", "consistent", "indicates"],
        "conclusion": ["combination", "compress", "noise", "degrad", "provenance", "watermark"],
    },
}

CLAIM_TEXT = "Post-processing degraded provenance, making the disputed image untraceable."
CLAIM_SUPPORTING_EVIDENCE = {"EV-002", "EV-003", "EV-004"}
REPORT_MIN_GROUP_HITS = 2

HINTS = [
    {"level": 1, "penalty": 5,
     "text": "Start by establishing what normal verification looks like — generate and verify "
             "a clean baseline before judging anything else."},
    {"level": 2, "penalty": 10,
     "text": "Compare the same underlying image before and after a transformation, rather than "
             "judging each result in isolation."},
    {"level": 3, "penalty": 15,
     "text": "Try testing each transformation individually first, then try combinations — "
             "watch for which approach causes the biggest drop."},
    {"level": 4, "penalty": 20,
     "text": "No single transform crosses the threshold on its own. The compounding effect of "
             "multiple transforms together is what matters."},
]

SCORE_WEIGHTS = {
    "investigation": 20,
    "evidence": 15,
    "reasoning": 20,
    "knowledge": 15,
    "final_report": 25,
    "efficiency": 5,
}

SKILLS_DEMONSTRATED = [
    "AI Security Fundamentals",
    "Watermark & Provenance Forensics",
    "Threat Investigation",
    "Evidence Analysis",
    "Attack Chain Reconstruction",
    "Mitigation Design",
]

REMEDIATION = [
    'Use robust, redundant watermarking resistant to common image transforms.',
    'Combine watermarking with cryptographic provenance (e.g., content credentials/C2PA-style metadata).',
    'Monitor for outputs re-appearing without valid provenance.',
    'Contractually and technically detect resale, not just discourage it.',
]
